### ISSUE TITLE
Update prod deployment github action to align with mcp-dev github action

### ISSUE THREAD

**Issue by chuckwondo** [NASA-IMPACT/hls-orchestration#266]
## Tasks

Repo: https://github.com/NASA-IMPACT/hls-orchestration

- [x] ~~Create bucket replication for Prod (like for mcp-dev).~~ Update bucket policy (which bucket?) to allow s2 downloader to write directly to the MCP bucket, rather than setting up bucket replication. (see https://github.com/NASA-IMPACT/hls_development/issues/235)
- [x] Update `production-deployment.yml` to align with `mcp-dev-deployment.yml`
- [x] Create `mcp-production` GitHub env to align with `mcp-dev` GitHub env
- [x] Temporarily disable listening to Landsat SNS topic to avoid initially listening in MCP Prod deployment when first deployed

**Comment by chuckwondo** [comment]
@sharkinsspatial:

- I've created the `mcp-production` GitHub env. Where I wasn't sure what the correct prod value should be, I simply copied the value from the `mcp-dev` env. Please take a look and let me know what should be updated (or just go ahead and update them): https://github.com/NASA-IMPACT/hls-orchestration/settings/environments/2213726465/edit
- Regarding the bucket that we want to allow the s2 downloader to write to directly, just to confirm, the bucket is based upon the stack name (i.e., it is _not_ an env var), so for `mcp-production`, `HLS_STACKNAME` is `hls-mcp-production`, so the bucket would be `hls-mcp-production-sentinel-input-files` (created upon initial deployment). Is this the bucket that we want to add cross-account permissions?
- For the cross-account permissions, I know we discussed manually applying the permissions, but given that the bucket is managed by the stack (assuming the previous item is correct), I'm thinking it might be better for us to include the permissions as part of the stack. What do you think?

**Comment by sharkinsspatial** [comment]
- @chuckwondo I'll try to review the `mcp-production` environment settings today.  The ECR image tags we use in production are different and I will update them accordingly 👍 

- Correct. The bucket has the stack name as a prefix so `hls-mcp-production-sentinel-input-files` is the bucket we want to add cross account permissions to so that the s2 downloader can write to it directly.

- I'm not sure on this front, I don't know in MCP if we have rights to change a bucket policy (even on a resource we create as part of our stack).
-

**Comment by sharkinsspatial** [comment]
@chuckwondo I've updated the ECR image values for the `mcp-production` environment so this environment should be correct now and ready when we want to deploy the stack.

**Comment by chuckwondo** [comment]
Completed via #269
